language: objective-c

branches:
 only:
 - master

xcode_project: BluetoothTest.xcodeproj
xcode_scheme: BluetoothTestTests
osx_image: xcode7
xcode_sdk: iphonesimulator8.3 

script:
- xcodebuild clean build test -workspace BluetoothTest.xcworkspace  -scheme BluetoothTestTests -destination 'platform=iOS,OS=9.0,name=iPhone 6'
