language: objective-c

branches:
 only:
 - master

xcode_project: BluetoothTest.xcodeproj
xcode_scheme: BluetoothTest
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

script:
#- xcodebuild clean build test -workspace BluetoothTest.xcworkspace -scheme BluetoothTest -destination 'platform=iOS Simulator,OS=9.0,name=iPhone 6'
- xcodebuild clean build -workspace BluetoothTest.xcworkspace -scheme BluetoothTest
